- name: cart
  hosts: cart
  become: yes
  tasks:

  - name: disable old nodes and enable nodejs18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creat roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove app
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart app
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: extract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: integrating redis to cart server
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true


  - name: cart service enable and start
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes