- name: catalogue
  hosts: catalogue
  become: yes
  tasks:

  - name: disable old nodes and enable nodejs18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creat roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove app
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue app
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: integrating mongo to catalogue server
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: load schema
    ansible.builtin.command: mongo --host mongodb.blackranger.xyz < /app/schema/catalogue.js

  - name: catlogue service enable and start
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes