- name: catalogue
  hosts: catalogue
  become: yes
  tasks:

  - name: disable old nodes and enable nodejs18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package
      name: nodejs
      state: present