- name: catalogue
  hosts: catalogue
  become: yes
  tasks:

  - name: disable old nodes and enable nodejs18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creat roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: creat a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue app
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
